### ISSUE TITLE
Direct Connect Mode with RS_ASIO, worth bothering with?

### ISSUE THREAD

**Issue by zagatozee** [mdias/rs_asio#105]
I'm not sure how this would be "useful" But with the recent discovery of the hidden "Direct Connect" mode, that accepts any input the game can see as a microphone and works with the tone effects applied, is there a way that can be used with the ASIO mod to give users a few more in game options - or is it totally invalidated by the fact the RS_ASIO can work on 2 inputs already and appear to the game as 2 Real Tone Cables?

Small write up at the start of this TRR post, but if you want more info on how DC mode works (or can be enabled),I'd  be happy to discuss.
https://theriffrepeater.com/rsmods-but-what-is-direct-connect-mode-mods-pc-mac-steam-custom-tuning-setlist-cables-interfaces/

**Comment by mdias** [comment]
Thanks for the link, I was unaware of this mode.
I haven't tried it, but from reading the article, it seems there is nothing to gain from enabling DC mode and having RS_ASIO too. And since DC is really only applicable to player 1, you could end up with the case that RS_ASIO would be unable to work for player 1 since that reports back to the game as being a RTC cable, and it's possible that DC mode ignores the RTC cable for player 1.
