### ISSUE TITLE
No audio output when Audio exclusivity disabled.

### ISSUE THREAD

**Issue by HardCorpse** [mdias/rs_asio#113]
When I disable audio exclusivity I receive an error message.

Error sound initialization.
No audio output device is detected. Please connect and enable an audio output device then restart Rocksmith 2014.

The error goes away with I remove the patch files.
My sample rate is 48k and the error is there regardless of which output I use.

**Comment by mdias** [comment]
From the README:

> Make sure Rocksmith.ini is set to run with `ExclusiveMode=1` and `Win32UltraLowLatencyMode=1`.

**Comment by CptnMangol** [comment]
Folks-

I was having trouble with Rocksmith 2014, not having any input or output. I read a bunch of things that talked about modifying the Rocksmith.ini file, and changing the quality level, but now of those things worked. What ultimately worked for my situation was the following:

Windows 10-

Windows Key - type 'Sound Settings', then scroll down to "Advanced Sound Options" and click on "App Volume and Device Preferences". Now launch Rocksmith (I suggest launching it in Window Mode instead of Fullscreen - under Options, Video Settings of Rocksmith). Once you launch Rocksmith, it will appear. Then all I had to do was set Output to "Speakers" and Input to "Rocksmith USB Guitar Adapter"

Best of Luck and Rock On! -CptnMangol

![AudioApp](https://user-images.githubusercontent.com/98631423/151646974-dbcc7742-d360-4d11-90a0-f33bb87bd008.JPG)
