### ISSUE TITLE
(NOT AN ISSUE JUST COULDN'T FIND APPROPRIATE SPOT)M-Audio Audiophile USB Interface

### ISSUE THREAD

**Issue by f0rmald3hyde** [mdias/rs_asio#122]
Hey everyone. Hope your all having a great night, I can't quite find the right spot to post this so I apologize that this is in the issues forum. But I've been using a Roland Cakewalk V-Studio 20 for the last few years as my audio interface as it has a built in COSM chip and allows me to use it as an effects board, amplifier and amidi controller for DAW software, as much as I love this thing it can be a pain to use and doesn't support 48khz audio or Windows 10 without hacking the drivers (thanks Roland!). So along with the the fact that RS requires a 48khz audio I had to resort to my trusty friend, my old audiophile from 2003 and i would like to confirm that this works just like a dream, the only issue i had was tuning but in the end that turned out to be an issue with my interface and rocksmith with my jackson (not an issue for the garbage cable lol) and neither my ibanez bass or my les paul. Other than that I've had no real issues with it. If anyone else would like to try a test and confirm that it works well feel free too. Once again I apologize for this being in the incorrect spot.

EDIT: After more work I had realized that I had a minor intonation problem and I had did some tweaking to my guitar and have alleviated my issues with tuning. This mod is amazing, i really wanted something like this way back in 2015/16. I probably wouldn't have dropped RS after my second realtone cable broke down on me. Great work bud!

**Comment by mdias** [comment]
Hey! No problem to post here, but if you want general help with something I would recommend you post in [/r/rocksmith](https://www.reddit.com/r/rocksmith/) as there's a lot more people in there that will look at your post.

I've not yet seen any tuning issues that are actually related to RS_ASIO, which is expected as this is only "redirecting" the audio from your interface to the game and if you hear it fine ingame, then RS_ASIO should be working just fine.

It seems you've figured out yout issue though. However if you need more checking, I would recommend you pause the game in the middle of a song, and in the pause menu you should see in the bottom left corner of your screen the notes that you're playing. There you'll be able to double-check your intonation and make sure the right notes are being detected.
Since you seem to have been able to fix the issue, I'm closing this issue, but feel free to re-open it if needed.
