### ISSUE TITLE
Behringer UMC404HD working perfectly!

### ISSUE THREAD

**Issue by KarmicLuca** [mdias/rs_asio#13]
Hi, thank you so much for your work! I've spent the longest time trying to make use of my usb interfaces with Rocksmith, and had to use crazy workarounds because nocable patch was giving me headaches.

This works amazing! Took a little while to find the proper name of the interface, but then I noticed the ASIO driver name in the log, and BAM everything works! 
I also think ASIO likes to have the device disabled in windows audio panel.

Love that you can select every single input, as wasapi interprets this 4 inputs interface (Behringer UMC 404HD 192k) as two pairs of inputs, which has annoying consequences in many applications.

So, here's my configuration file for anyone who may need it! Using latest drivers from Behringer site.

Cheers!

```
[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=128

[Asio.Output]
Driver=UMC ASIO Driver
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=UMC ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by mdias** [comment]
Thank you for the report. Glad it's working fine for you :)

**Comment by noghiri** [comment]
I had issues with KarmicLuca's config for my specific use case. The two things I found that helped were launching the game with Discord completely closed (it interacts oddly with audio drivers sometimes) and changing the config to use WASAPI for output.  
You may want to use WASAPI for output if you're streaming and OBS or similar isn't working right with ASIO out, or are having trouble with ASIO out working reliably due to driver version.  The tradeoff is that this can add some output latency, which can mess with your sense of where the beat is.
Here's the config that I got working, as based on KarmicLuca's:
```
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=
BaseChannel=1
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=UMC ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```
Additionally, for future people who wander through here looking for solutions to the same issues I had - set Channel under `[Asio.Input.0]` to 0 for Input 1, 1 for Input 2, etc.  If you're not getting audio recognized, make sure your guitar is plugged into the right port - this applies to all interfaces supported by this mod, and should be relatively obvious, but I managed to miss this for 15 minutes while trying to get the configuration right.

**Comment by toadm2h** [comment]
Many thanks!
After few hours works for me with "Input 2" on device (turned off all record devices except "IN 1-2" on device panel (run in command line "control /name Microsoft.Sound")):
`[Config]
EnableWasapi=1
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=64

[Asio.Output]
Driver=UMC ASIO Driver
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=UMC ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
`

**Comment by Agithos** [comment]
Thank you for this! By the way, as noghiri has said (which I missed) :  Channel 0 is corresponding to Input 1 on the interface (etc..)
