### ISSUE TITLE
No audio output device is detected. Please connect and enable an audio output then restart Rocksmith 2014

### ISSUE THREAD

**Issue by notnoam** [mdias/rs_asio#139]
Hello
i recently downloaded RS_ASIO and placed it where it should and how it should 
as i want to launch the game (after i do the thing with the log and the .ini file) i launch it and i get the message of No audio output device is detected. Please connect and enable an audio output then restart Rocksmith 2014
my gear is - M-Audio M-TRACK 2X2, Logitech G Pro X headset,fender play strat 
just mentioning my game worked fine before the rs_asio thingy

**Comment by mdias** [comment]
I need to look at your log file and configuration file to have an idea of what is going wrong.

**Comment by notnoam** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/5614323/RS_ASIO-log.txt)
[Config]
EnableWasapi=1
EnableAsio=1
[Asio]
BufferSizeMode=driver
CustomBufferSize=0
[Asio.Output]
Driver=M-Audio M-Track 2X2 ASIO
EnableSoftwareEndpointVolumeControl=0
EnableSoftwareMasterVolumeControl=0
SoftwareMasterVolumePercent=0
[Asio.Input.0]
Driver=M-Audio M-Track 2X2 ASIO
EnableSoftwareEndpointVolumeControl=0
EnableSoftwareMasterVolumeControl=0
SoftwareMasterVolumePercent=0
Channel=1
[Asio.Input.1]
Driver=
EnableSoftwareEndpointVolumeControl=0
EnableSoftwareMasterVolumeControl=0
SoftwareMasterVolumePercent=0
Channel=0
i also tried the Realtek device as output but didnt work

**Comment by mdias** [comment]
In this log I can see that your ASIO driver seems to be working correctly, however the game is deciding not to use the ASIO output, probably because you have `EnableWasapi=1`. You should try with `EnableWasapi=0`. It will then output the audio through your M-Audio interface.

If this doesn't work, please post the log with `EnableWasapi=0`.

If you actually want to use Wasapi (to use your realtek device for audio output) make sure that device is set to default output device in windows and leave the `Driver=` setting blank on the `[Asio.Output]` section.

**Comment by notnoam** [comment]
Changed the EnableWasapi to 0 and it worked. ty

**Comment by mdias** [comment]
Awesome! No problem, and sorry for the delayed reply. 👍
