### ISSUE TITLE
Setting up Audio with ASIO4ALL

### ISSUE THREAD

**Issue by pigatt** [mdias/rs_asio#142]
Hello Guys,

This is not issue which has to be solved by developer, because basically RS_ASIO is working properly!
So I have an M-Audio AIR 192-4, which is working fine, with its own ASIO driver, but this driver an unstable sh*t! I am after a long e-mail conversation with M-Audio, and they recommend to use ASIO4ALL. But I am not able to set it up correctly, because my audio playback is so bad, with ASIO4ALL, it is distort and slow!
Maybe somebody who is using ASIO4ALL, too can tell what am I doing wrong! 
Here are my configurations:

Rocksmith.ini:
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=2560
ScreenHeight=1440
Fullscreen=2
VisualQuality=2
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1

RS_ASIO.ini:
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=256

[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=ASIO4ALL v2
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

In ASIO4ALL Offline settings, I just set the buffer size to 256 Samples not more.

Thanks for your help in advance!

**Comment by pigatt** [comment]
I went down with buffer size to 64 (ASIO4ALL 2.14 not support lower value! :)) The quality is much better now, but far not perfect, I think with buffer size 32 would be fine, but I cannot set, even it runs in 64, if put custom 32 buffer.

**Comment by mdias** [comment]
ASIO4ALL is not a replacement for a "proper" ASIO driver. It basically emulates the ASIO interface on top of WDM.
What this means is that if your WDM drivers don't handle 64 buffer sizes (or lower) properly, then that will be your bottleneck.

Also, it may be the case that in this instance it makes little sense to run ASIO4ALL when you could just use the game's native audio output (WASAPI) which may already get you good results.

RS ASIO makes more sense with true ASIO drivers (that bypass the whole windows audio stack) and if you're not using it with such drivers you're probably better off using other methods like the NoCableLauncher or Direct Connect mode. If you choose to go this route I recommend you look for help on [reddit/r/rocksmith](https://www.reddit.com/r/rocksmith/).

Otherwise if there's a specific reason you still wish to use RS ASIO with ASIO4ALL let us know.

**Comment by zagatozee** [comment]
I like to refer to asio4all as Google translate for ASIO only software and non-ASIO compliant hardware. It gets the job done in a pinch, but it really is NOT great.

I'd also be leaning towards Direct Connect mode with that interface, but you may hit an issue with the input numbering. Rocksmith and DC mode, only wants to work on the first input. ( MDias, if you have any ideas how we might be able to hack that and make RS see the inputs we want it to, I'd love to hear about that)

The easiest way to get DC mode up is as part of the https://bit.ly/RSModsGit project.

**Comment by pigatt** [comment]
The best would be a proper driver, I really sorry that interface, because when it works it is great! Now I went back to real tone cable, but it sounds so bad after the 192-4!

**Comment by mdias** [comment]
Ahh indeed the input index will be an issue without RS ASIO.

@zagatozee While this isn't a technically very complex problem to solve, it is something that would require a very significant amount of time and effort to accomplish properly. It's not impossible that there's a workaround I can't think of right now, but otherwise to be done properly this would need to again re-implement some translation layer between true WASAPI and the "fake" WASAPI exposed to the game, so you could almost say this would double the scope of this project.

@pigatt  So yeah, unfortunately there's nothing I can currently do about this. What kind of instability does the ASIO driver have? Is it only unstable with RS ASIO or with all other ASIO-enabled software?

**Comment by pigatt** [comment]
It is unstable in any cases! To keep it simple as I think this manufacturer drivers has two parts a WDM part and the ASIO. Mostly under daily WDM usage (Youtube, gaming, music, etc.), sometimes the sound quality turns that distort, which you can hear in the link below (my recording). The error appears only when the interface "remix" the audio (starting a playback, jumping into a video, it can come only by a single Windows notification sound, etc.). The internet is not full with that issue, so I think it is not a common issue, even the manufacturer cannot said anything on merits. :(
I tried a lots of things with setting and with an another interface (M-Audio 192/6, same as mine, but only with more IO), it behaves exactly the same, but during this mine was working fine with an another PC. But without the manufacturer driver, so if I am using the device as Windows recognize it, I don't have a single problem with audio playback quality, but in this case, I don't have ASIO!

[https://drive.google.com/file/d/11EGvdZlqsU0UlYAdJ8wOboK6O64oB7H9/view?usp=sharing](url)

**Comment by mdias** [comment]
I see, it does sound pretty bad :/

I'm sorry I really have no good ideas to help you with this. But if the interface works fine with some other PC at least not all hope is lost. Perhaps the problem could be solved with a simple fresh windows install, or maybe plugging the interface into a different USB port; maybe even a USB hub like your monitor (if it has one).
If your driver has settings to play with the buffer size (not just for ASIO) then maybe increasing it may help, and/or reducing the sample rate from 192k to 48k if you're using something very high. If - as you say - the problem seems to appear when mixing audio streams it could very well be that this is the problem.

**Comment by pigatt** [comment]
I am strugling with that issue since the beginning! I tried to reinstall Windows, use other USB ports (2.0 Type A, 3.0 Type, 3.1 Type A, 3.1 Type C, 3.2 Type C), use USB hub, use PCIe USB extension card, unfortunately none of these helped! 

And one more symptome which I can solve, but I don't undestand how can it happen!
So the interface is stable when I don't install the M-Audio driver, if I install the manufacturer driver and I connect the interface to USB Type A with ASmedia USB controller, the audio will sounf like this:

https://drive.google.com/file/d/1rd7riL3lH3Ll8dXY5V3wCQaXIGtU4BTX/view?usp=sharing

So it is different from the other issues, but still bad! I have to install the ASmedia driver to solve the issue, which is intersting, because Windows 10 as I know supports nativly this version of USB standards, because of this the motherboard manufacturers doesn't provide dedicated USB controller drivers!

I never believed incompatibility issues, but now I don't know what to do, but it is really annoying that I cannot find the source of the issue, and even the issue itself really annoying! 

But now we are very far from the original question, so I think you can close the thread!

**Comment by mdias** [comment]
Yeah, sorry I couldn't be more helpful...
