### ISSUE TITLE
Axe I/O works perfectly

### ISSUE THREAD

**Issue by siegmour** [mdias/rs_asio#147]
Reporting that [IK Multimedia's Axe I/O](https://www.ikmultimedia.com/products/axeio/) works perfectly with RS_ASIO. Everything is working as expected, including the buffer size change without ASIO control panel via the ini.

For users of the interface: Just make sure you have the Axe I/O Control Panel installed (which are the drivers). The required name in the RS_ASIO.ini is "AXE IO ASIO". Channels are expected, e.g. 0 in the ini is channel 1 on the interface.

With this interface, my game runs with LatencyBuffer 1 in Rocksmith.ini and buffer size of 64. CPU is Ryzen 2700X. Interestingly to note, if the buffer size is  too high (for example 256), I will get audio crackling with LatencyBuffer 1. 

Thank you very much for your work on this project! It is very appreciated!

**Comment by mdias** [comment]
Thank you for the report. Added to the list 👍

**Comment by KingOfTacoAndGuac** [comment]
I have the AXE I/O ONE, and it works just fine with that too.  The only differences are the name in RS_ASIO.ini (AXE IO ONE), and having to run the game with a higher latency buffer because the ONE defaults to a buffer size of 512.  I think you can change the buffer size in Amplitube, but I'm not worried about it because there's no latency and everything sounds amazing.

**Comment by KingOfTacoAndGuac** [comment]
This also works with the newer AXE I/O ONE if anyone has that.
