### ISSUE TITLE
Behringer UMC22

### ISSUE THREAD

**Issue by nate-higgers** [mdias/rs_asio#165]
This is the log I get using the interface in the title

0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
0.318 [ERROR]  No valid locations for patching were found. Make sure you're trying this on the right game version.

The guide says the patch only works for the Steam version but I'm using a pirated version of said Steam version. I tried moving the game's install directory to my default steam games directory located @ "C:\Program Files\Steam\steamapps\common\Rocksmith 2014" but no avail. Do I actually _need_ to buy and use a legit copy or is it an issue with the interface?

System: Windows 8.1 64 bit
DAC: Behringer UMC22.
note: I did install the asio4all drivers for it and it seems to work just fine on my DAW.

**Comment by mdias** [comment]
Yes, you need a non-pirated copy of the game.

As for your interface, as long as it has ASIO drivers (not just ASIO4ALL) it should work fine. If it uses ASIO4ALL it may or may not work properly.

**Comment by Cussa** [comment]
Working with the UMC22. Used the instrument input on the audio interface, using the ASIO4ALL driver (currently the "default" Behringer driver).

# Config Files

## RS_ASIO.ini
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

## Rocksmith.ini

```
[Audio]
ExclusiveMode=1
LatencyBuffer=4
ForceWDM=0
MaxOutputBufferSize=0
Win32UltraLowLatencyMode=1
```

**Comment by zagatozee** [comment]
ASIO4ALL? Please don't.

See the link in the reddit auto mod for the "proper" ASIO drivers for Behringer gear. 

https://www.reddit.com/r/rocksmith/comments/r5oq4b/asio4all_and_default_soundcard_from_my_motherboard/hmo2rus/

**Comment by Cussa** [comment]
@zagatozee I didn't know that. But there is a question: any reason to avoid the Asio4all? Because as far as I saw, it seems that is working properly. Of course that I didn't reach the point to verify how to set up OBS, and maybe it will make a difference..

**Comment by mdias** [comment]
Native ASIO drivers (assuming good quality ones) gives the software that uses them a more direct path to the hardware, usually reducing latency and overall performing better.
ASIO4ALL is built atop of another driver layer and that usually results in higher latency or other issues. Since people using RS ASIO are generally looking for the best experience, people usually suggest staying away from ASIO4ALL.

That said, if it works fine for you and you don't notice any latency or other issues, then maybe it just happens to run great on your system.

**Comment by Cussa** [comment]
After the talks here, I changed to the "old" drives and tried to use it with Reaper, so I can capture it on the OBS.

However, even that it was working, I was hearing some crackling on it. I will try to stop tomorrow/this weekend to go again over the complete set-up to try to fix that.

**Comment by mdias** [comment]
Thank you for trying that out. If you find that it also works fine with direct usage of the "old" drivers (without going through Reaper), please let me know and I'll add it to the list of devices known to work fine.

The crackling might just be buffer size being too small or something. If that's the case you should have some log messages (on RS_ASIO-log.txt) mentioning buffer underruns.

**Comment by Cussa** [comment]
Sure! I will try to do a test tomorrow and post here the results.

And I didn't know that it had some logs about the buffer! I will take a look on it, because I am watching the VOD from the stream and I can hear sometimes the cracklings.

**Comment by Cussa** [comment]
UMC22 working direct.

## RS_asio.ini
```ini
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=BEHRINGER USB AUDIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=BEHRINGER USB AUDIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

## Rocksmith.ini
```ini
[Audio]
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
MaxOutputBufferSize=0
Win32UltraLowLatencyMode=1
```

**Comment by mdias** [comment]
Awesome! Added to the list 👍 
Thanks!

**Comment by Cussa** [comment]
@mdias I am having some issues to configure it with the ReRoute, as I need it to put the sound in OBS.
Or at least, it was the solution that I found. There is any kind of help that you or someone could give?

**Comment by mdias** [comment]
I've personally never configured it with ReRoute, only with Voicemeeter.
You can check out [this page](https://github.com/mdias/rs_asio/blob/master/docs/streaming/README.md) on the documentation where you can find some information and even a video tutorial.

**Comment by Cussa** [comment]
@mdias I will probably open a new ticket especifically for that to see if I am able to get some help. In the final, to be able to play, I am trying to use the reaper only for the input of the guitar (so I can use some VST plugins on it), but the directly interface for the output. However, I had to do some configuration turning off the low latency to be able to get the audio in the OBS.

I followed both tutorials that you send and in the final, I believe that the issue is related to Reaper/ReaRoute and not with the plugin here, as it's working properly without reaper

**Comment by mdias** [comment]
You may have issues doing that due to having 2 applications trying to use the same interface through ASIO. However this depends on your ASIO driver implementation allowing it or not.
As far as I remember what people did to retain sound in OBS was use voicemeeter as a middle man between RS ASIO and your interface, and then Voicemeeter can also feed a virtual input device with the output signal that comes from the game. This virtual device is then useable by Voicemeeter.
Now throwing Reaper into the mix shouldn't be too complicated, I assume what Reaper does is change the sound in whatever way and feed it back to the (in this case virtual) voicemeeter device, and then you can route that signal however you want.

Keep in mind though that the signal RS ASIO *receives* should still be non-distorted signal so that note recognition works fine ingame.
