### ISSUE TITLE
Can I make it work with katana, but to output the backing track through my PC speakers?

### ISSUE THREAD

**Issue by eliezra236** [mdias/rs_asio#184]
Hi,
I am trying to use rocksmith and set up my Katana for my guitar tone, that way I get to practice different amp settings and hear myself better, but to use my PC speakers as the output for the backing track.
I couldn't really understand this - https://github.com/mdias/rs_asio/blob/master/docs/katana_mk2/README.md
Sorry for my ignorance about it, I am pretty new to:
1. guitar
2. mods
3. rocksmith
4. audio interfaces

I manage to use Asio4all to make the amp work with BIAS FX the same way. it recognizes my guitar if I want to use the BIAS FX settings, and I can also hear myself through the amp (I turn the amp to standby mode if I just want to hear myself through the PC speakers with the BIAS FX settings).

**Comment by mdias** [comment]
Yes you can.

To achieve this you leave the `Driver=` config of the `[Asio.Output]` section blank, and use `EnableWasapiOutputs=1`.
This will make the game use the "standard" audio output, while still using your Katana as input.

The configuration file you linked to appears to mention some extra setup for the input to have acceptable volume level. I won't be able to help you much with that though since I don't own that interface myself and the config was added by someone else.

**Comment by eliezra236** [comment]
I am getting "no output device detected, and when I skip that and go into the game I am getting "no real tone cable detected" =/

**Comment by eliezra236** [comment]
I got it to work, turns out on my rocksmith.ini I had exclusive mode turned off.
But now it's fixed.
Thank you so much for making this, you are awesome!
