### ISSUE TITLE
Game isn't properly releasing ASIO driver on ESI MAYA44 EX

### ISSUE THREAD

**Issue by loddurr** [mdias/rs_asio#185]
After closing the game, the ASIO driver becomes unavailable for every other program utilizing the ASIO driver, including the game. Now, I've seen the already posted issue involving this internal sound card, you advised to contact the Devs, but they can't help me as they say they haven't reports of such issues with other programs, like DAWs or other standalone software.

I have to say, no audio program I have installed (Cubase, Reaper, NeuralDSP, Guitar Rig) causes that issue, even if I "simulate" a crash by closing the task or disabling the driver etc. it's always possible to re-initialize the driver.

As it is an internal PCI-Express soundcard, I haven't found a way to re-initialize the driver besides restarting my computer. Do you know of a way to have that same process without restarting? Is there any command on Windows to restart the PCI-Express slot or something? I think that would solve the problem.

Maybe it's not solvable by you, as maybe Ubisoft just has a bad coded engine not shutting down the driver properly and hogging it until you restart Windows.

Anyways, it's just a minor inconvenience, but for example, I have to restart my stream when I start streaming with Rocksmith and want to transition to something else, like playing to Youtube Backingtracks or something.

including my RS_ASIO log.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/6391274/RS_ASIO-log.txt)

ASRock B450M Pro4 on latest BIOS
Ryzen 5 3600X
32 GB DDR4 1333 RAM
Gigabyte RTX2070S
ESI MAYA44 EX
Microsoft Windows 10 Pro Version	10.0.19042 Build 19042

Latest rs_asio and Steam Rocksmith version.

**Comment by mdias** [comment]
I think I remember seeing this reported about that interface before.

I'm not sure if there is anything I can do or not; due to lack of access to RS source, it's hard to tell if it's something the game is not doing right, or if it's RS ASIO not doing something right. The truth is that it doesn't matter much, since the drivers shouldn't remain in a locked up state even if some application misbehaves.

But what matters is trying to solve this inconvenience. The only idea I have in mind is also somewhat inconvenient, but less so than having to reboot the computer.
Instead of using the ESI ASIO driver directly, you could put Voicemeeter inbetween the signal chain (have RS ASIO configued to use Voicemeeter ASIO driver, while Voicemeeter just forwards the input and output signal directly to your interface.
This will isolate any problems the game or RS ASIO might create and let the device initialization/uninitialization happen on Voicemeeter side alone, which hopefuly doesn't lock up your stuff.

RS ASIO uses a non-standard way of communicating with ASIO drivers too due to some technical issues that arise from this being a "hack", so it's not impossible that that may be the root cause of the issue with some drivers.

**Comment by loddurr** [comment]
That works perfectly with Voicemeter! Thanks for letting me know! Yea, like Cantabile I use for streaming, Voicemeter also shuts down the driver without issues - and Rocksmith recognizes the Voicemeter ASIO driver just fine!

I suppose this case is solved then!
