### ISSUE TITLE
Rocksmith crashing at Ubisoft logo on launch

### ISSUE THREAD

**Issue by unclebaz** [mdias/rs_asio#194]
Hey there. So I was using RS Asio for Rocksmith in early April, I was using it with Voicemeeter and had it running well during streams. I tried to play the game 2 weeks later in early may and the game just started crashing immediately on Launch at the little pick logo in the bottom right corner. I've reinstalled the game multiple times, re setup RS Asio and RS settings multiple times with no launch. I must add though; the game launches when my Audio Interface (Focusrite Solo Gen 3) is unplugged. I have uninstalled and reinstalled the Scarlett drivers, still no luck. Been trying to get help from the guys in RS Cord, but no one has a solution or any idea what the problem is. Really need your help, miss playing the game lol.

**Comment by unclebaz** [comment]
my RS_Asio.ini file looks like this: 
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by unclebaz** [comment]
and this is my RS_Asio-log
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/6595083/RS_ASIO-log.txt)

**Comment by mdias** [comment]
It is indeed strange. Everything looks good on your log.
Is the interface working fine with any other ASIO software? If so, I'd suggesting using the Voicemeeter ASIO driver instead and use Voicemeeter software to route the audio to/from your interface if that works.

It could be some software that you installed meanwhile or even some updated drivers that are now misbehaving for some reason. It could also be a bug on RS ASIO itself, but unfortunately it will be near impossible to do anything about it since I don't own that interface and it seems no one else is getting this issue.

In any case if routing the audio through voicemeeter works, then you should be able to play the game just fine and you shouldn't notice any difference compared to using the Focusrite driver directly.

**Comment by unclebaz** [comment]
Interface works buttery with everything else. I usually do route the game through Voicemeeter (since I was streaming the game) but unfortunately this issue with my Interface has just disallowed me to stream the game. Everyone is unsure on what it is, and that sucks because I enjoyed playing the game. Thanks for the reply

**Comment by unclebaz** [comment]
Also I don’t think routing through Voicemeeter will fix anything, since the game just won’t launch at all with my interface plugged in which is the weird part, yet early April it worked fine

**Comment by Progig01** [comment]
I have a very similar story to tell, almost down to the letter. The only major difference is my interface is a Behringer U-Phoria UMC204HD, So much as having it plugged in causes my game to crash. I've tried the entire list of basic troubleshooting stuff, test interface in other software, no problems. Reinstall rocksmith, making sure to delete all left-behind files after steam uninstall, reinstall rs_asio, no luck, still crashes. Reinstalling and trying several versions of my Interfaces drivers, no luck either.

RS_ASIO.ini can be found here https://pastebin.com/y5Z3JBqY
RS_ASIO-log.txt can be found here https://pastebin.com/9tpWCTEJ

**Comment by mdias** [comment]
> 
> Also I don’t think routing through Voicemeeter will fix anything, since the game just won’t launch at all with my interface plugged in which is the weird part, yet early April it worked fine

Oh, so this happens with or without RS ASIO?

If it only happens with RS ASIO does it also happen if you don't specify the Focusrite drivers at all in the ini file?

**Comment by unclebaz** [comment]
Yeah happens with or without RS Asio so I have no clue

**Comment by Progig01** [comment]
Same here, seems to just be a rocksmith/windows thing. Maybe the latest windows update broke some stuff?

**Comment by mdias** [comment]
It's still a curious thing, because with RS ASIO if you have both wasapi inout and output disabled we don't even touch wasapi, so the audio related stuff happens only through ASIO, so it must be something else that goes wrong.

Try setting `DumpAudioLog=1` in your `Rocksmith.ini` `[Audio]` section, and then run the game. This should create a file `audiodump.txt` in your Rocksmith folder. Perhaps it may contain any hint? But probably not... Still wirth a try.

**Comment by unclebaz** [comment]
00000000:  : INIT ExclusiveMode 0
00000000:  : INIT LatencyBuffer 4
00000000:  : INIT ForceWDM 0
00000000:  : INIT ForceDirectXSink 0
thats what my audio dump file says

**Comment by mdias** [comment]
Right,  there's no relevant information to the crash here, but it is showing something you have misconfigured.

You should have `ExclusiveMode=1` on your `Rocksmith.ini` as stated on the readme, and it seems you're not using exclusive mode. I don't expect this to fix the crash, but in any case you'd need that for RS ASIO to work.

**Comment by dralanmage** [comment]
Do you happen to be running Linux? I have a very similar crash in the exact same manner as described that suddenly started happening after a Linux kernel update. Reverting to the prior kernel made the issue go away.

**Comment by unclebaz** [comment]
nah windows mate
