### ISSUE TITLE
Uninstall Audio Issue (need help)

### ISSUE THREAD

**Issue by lootdaddy** [mdias/rs_asio#203]
Hi, I am wondering if anyone has a solution to this.

I tried to uninstall RS_ASIO so I could use the Realtone Cable (easier for steaming). I deleted the RS_ASIO files from the game, but this made it so it would no longer start. The error said that RS_ASIO was missing. I then uninstalled the game on steam + the leftover assets and downloaded a fresh copy.

Upon launching, I immediately noticed that the audio was stuttering BADLY. Game is completely unplayable. Nothing has worked, I have uninstalled and reinstalled the game multiple times. Verified game file integrity multiple times. I even tried deleting the Rocksmith 2014 folder, and then verifying the game files in steam to reinstall that way. Still stutters endlessly.

Can anyone here help? I am new to Windows OS so this is totally out of my ballpark.

**Comment by mdias** [comment]
The reason you got the `Failed to load RS_ASIO.dll` error is because you didn't also delete `avrt.dll`.

As for the audio stuttering after you removed everything, it's completely unrelated to RS ASIO, so this is not the best place to ask.

In any case, you should post which audio device you're trying to use as well as howyou intend to run it with (exclusive mode or not).
