### ISSUE TITLE
Focusrite Scarlet buffer size 16 should technically be plausible, but does not work.

### ISSUE THREAD

**Issue by hideki2** [mdias/rs_asio#206]
Hello I was using briefly Rocksmith+ Beta and there, after some fidgeting around I was able to make a Scarlett device run with the buffer Size of 16 which wooow gave basically in perceivable latency. That means that it should maybe be plausible to pull of with your plugin after all? Just a reminder, all scarlet devices seem to work only with the buffer of 48,96 or 192. 48 is still quite noticeable latency. Anyway, would be great to take another look at the issue.

**Comment by mdias** [comment]
RS ASIO itself will work with any buffer size. The 48, 96, 192 issue is a Focusrite drivers or hardware specific issue where either the drivers or hardware misbehave when using other buffer sizes and would likely require double-buffering to be implemented on RS ASIO to work around it (while adding latency).

As for you noticing the difference between 16 and 48 I find that very hard to believe to be honest. a 48 sample size buffer on a 48kHz stream is literally 1ms, and that's not even the true latency you get since that is only the buffer latency and does not take into account the whole driver/usb/hardware stack.
A very large percentage of your latency is coming from USB itself, so don't fool yourself thinking that 16 will give you three times less latency than 48. That's not even close to be realistic. There are software tools out that will allow you to measure the true roundtrip latency if you connect your interface input to one output, and if you use it you'll see that the difference should be quiet small.

It's much more likely that other factors (such as improved game audio signal processing) are giving you the impression that the difference between 16 and 48 is big since you're literally comparing 2 different pieces of software.
Also check your `LatencyBuffer=` setting in `Rocksmith.ini`. Those will add to the latency,

There were measurements in the past regarding RS 2014 latency with ASIO, and it's much bigger than the buffer size we specify, but since there is a whole lot of things that might be happening and the game is a black box, it's very hard to pinpoint where the problem might lie. Check [here](https://github.com/mdias/rs_asio/issues/172) if you want to read more.

**Comment by hideki2** [comment]
Thanks for a very detailed reply, and yes, you are right. Turns out that the high latency I was experiencing was most likely due to using maxoutputbuffer=0 Which was probably running it automatically at something like 1024 or 2048. I have manually set it to 48 and can't really detect any latency. I am very thankful for the reply and if what I just said about maxoutputbuffer does not make any sense, you are very welcome to tell me off. You sir have my at most respect.
