### ISSUE TITLE
Exclusive Mode Issue

### ISSUE THREAD

**Issue by TheExeQ** [mdias/rs_asio#216]
Is there a way to use this mod without Exclusive Mode on? Im trying to have other apps like discord on while im playing so i can talk with friends but im not able to hear them when the game is on. From goolging about this issue it seems like its caused from "ExclusiveMode=1" so is it possible to use the mod without exclusive mode?

**Comment by mdias** [comment]
Using ASIO requires Exclusive Mode, however this is not the same as the Exclusive Mode without RS ASIO.

If you're not using `EnableWasapiOutputs=1` then whether other apps can use your audio interface depends on the audio interface itself and/or its drivers.

Long story short, the very reason why ASIO provides lower latency is because it disables such features as multiple applications being able to use the same audio interface, so for most interfaces you're out of luck, unless you start playing around with complex audio setups.
