### ISSUE TITLE
presonus 24c issues unlcear output (crackling, noise)

### ISSUE THREAD

**Issue by sejoplejo** [mdias/rs_asio#217]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/7246816/RS_ASIO-log.txt
[RS_ASIO - Copy.txt](https://github.com/mdias/rs_asio/files/7246818/RS_ASIO.-.Copy.txt)
)

So, I'm pretty sure it's an easy fix somewhere, but I can't for the life of me figure out what is causing it.
I'm using the headphones out on my audio interface. The only available outputs in RS_ASIO-log.txt are (main) 0 and 1.
The input gets recognized, but the output is very noisy and unclear. No such issues on my DAW though.

I tried switching up the output channels with no success. Also tried going over my Bluetooth headphones connected to my PC with "enablewasapioutput=1" and leaving the output driver blank, but then I had a "no output recognized" warning in Rocksmith.

Any help is appreciated.

**Comment by mdias** [comment]
The log file doesn't appear to match the contents of your config file.
The log shows that you're trying to output through wasapi while the config file has no wasapi inputs or outputs enabled.

Make sure the proper `RS_ASIO.ini` file is being used.

Also your `[Asio.Output]` is specifying `BaseChannel=1` and you probably want `BaseChannel=0` since your interface only has 2 outputs (and you want to use output 0 and 1 for stereo sound output).

**Comment by sejoplejo** [comment]
Oh damn, my fault. Here's the updated files I just tested and confirmed to have crackling output over the headphone out on the audio interface:
[RS_ASIO - Copy.txt](https://github.com/mdias/rs_asio/files/7253526/RS_ASIO.-.Copy.txt)

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/7253527/RS_ASIO-log.txt)

**Comment by mdias** [comment]
You're having a ton of buffer underruns.
Use this on your ini file:

```
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=64
```

Basically the `BufferSizeMode=driver` is using your driver's settings for buffer size, which in your case appears to be 16 which is extremely low and very likely to cause the issues you're hearing.
The above setting (`custom` and `64` buffer size) should help a lot, but if that still underruns, try `128` instead of the `64`.

Also make sure your `LatencyBuffer=` setting in `Rocksmith.ini` (note this is not the RS_ASIO ini file) is `2` or more.

Only after you get these to values that give you good audio you can try and slowly lower them to achieve better latency if you notice any.

**Comment by sejoplejo** [comment]
that did the trick. Thanks for writing this piece of code and being so helpful with enduser incapablity lol. gonna send you a few bucks via your paypal 👍👍

**Comment by mdias** [comment]
Glad it worked for you!
Cheers for the donation 👍
