### ISSUE TITLE
No output with WASAPI

### ISSUE THREAD

**Issue by Th3BiSh0p** [mdias/rs_asio#227]
I'm trying to setting things up to stream my game.

RS_ASIO.ini
https://pastebin.com/x3JUaJnz

log
https://pastebin.com/KuViCXAg

When I launch the game, I have a popup saying I don't have any ouput device available (or something like that)

**Comment by mdias** [comment]
Do you have sound output without RS ASIO at all?
WASAPI output should do the exact same as the game does without RS_ASIO.

Please ensure your output card supports 48000hz audio, and post your Rocksmith.ini file too to double-check if eveything looks fine there.
Also post which audio card are you using for output.

**Comment by Th3BiSh0p** [comment]
Without RS ASIO I have sound output.

The sound card (a usb gaming set : RIG 800HD) is set to 24b 48khz.

rs.ini : https://pastebin.com/xcT67bxR
rs_asio.ini : https://pastebin.com/kn2UMU4E
rs_asio-log.txt : https://pastebin.com/BBgR2jzk

I just played a game session and it was working fine, so I thought I just messed to much with the settings and finally put the right settings. I stopped the game, and launched it again. It's not working anymore...

**Comment by mdias** [comment]
Your settings look fine.
Can you check if output works if you disable the Asio input? (just leave `Driver=` blank for all inputs in RS_ASIO.ini).

I'm unsure what's happening here because whatever device is being picked up by the WASAPI path is returning an invalid error when `IAudioClient3::GetDevicePeriod` is called. It's not impossible that it's picking up the same M-Audio device for output while it's trying to use it though ASIO at the same time.

**Comment by Th3BiSh0p** [comment]
I think my device is simply dying : https://github.com/mdias/rs_asio/issues/225
so no need to lose more time here, thanks for your help !
