### ISSUE TITLE
Recommended sample rate

### ISSUE THREAD

**Issue by withthelemons** [mdias/rs_asio#23]
This is not an issue but a question (although it would be nice if this was in README).

Should I set my interface to 48kHz sample rate or can I use different sample rate, eg. 96?

**Comment by mdias** [comment]
48kHz is the sample rate the game wants.

The reason it's not in the readme is because RS-ASIO does request the ASIO driver to switch to 48kHz, so even if you set your interface to 96, it should switch to 48 when you boot up the game.

I haven't seen yet any reports of this not working, but it's entirely possible that an ASIO implementation would disallow this switching, so it probably wouldn't hurt to add it to the README indeed.
