### ISSUE TITLE
Behringer Guitar 2 USB - Noise issues (no stuttering)

### ISSUE THREAD

**Issue by lkaupp** [mdias/rs_asio#246]
Dear mdias,

first, thank you so much for this mod! I bought a Behringer Guitar 2 USB cable (48kHz sampling rate) with an ASIO4all v2 driver. After I plug everything in and open the ASIO4all preference from tab and activate the UPnP Sound Device (Behringer cable) as input I can finally hear my guitar (as Rocksmith suggested everything maxed out [volume and tones]). Now, I have the problem that if I use the 100% volume setting for the ASIO driver (RS_ASIO) I get some kind of "ground" noise, that is always there after I play one of the strings. It seems it has something to do with Rocksmith internal added signal gain. It sounds similar to a maxed-out microphone gain if you use a headset. My solution atm is to lower the volume of the driver to 60%. The problem is now that is really hard to calibrate the guitar in rocksmith because it is too quiet. I set the sampling rate to 320 and tried different latency buffer values from 1 to 4 the problem stick the same.

 Any idea to eliminate the ground noise with the available parameters? Have you any idea what's causing the ground noise, the cable, or the guitar?

Edit://
I use my speakers as output so EnableWasapiOutputs is set to 1.

Edit2://
Ground Noise issue is not there using the through the standard WASAPI propagated "Microphone". Here the input lag is about to 1/2 - 1 sec which is just annoying and unplayable. So currently I exchange one issue for another. 

My config files:
Rocksmith.ini:
```
Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=1
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=3840
ScreenHeight=2160
Fullscreen=2
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
```

RS_ASIO.ini:
```[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=320

[Asio.Output]
;Driver=ASIO4ALL v2
;BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=60

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by mdias** [comment]
Return the volume percent to 100 and when your hear the ground noise go through the volume calibration on Rocksmith (that screen that asks you to play as loud as you can and then to mute your strings).
That should calibrate Rocksmith to clean up the noise that your guitar/cable makes when you're not even touching anything.

Note that this will only work if the noise is actually just the noise floor being a bit too high.

The SoftwareMasterVolumePercent is only really useful for when your volume is too low, not the other way around since Rocksmith volume calibration should be able to lower the volume as needed, unless you're already clipping in hardware in which case you have to use hardware knobs (like the one on your guitar, or audio interface if there is any) to turn down the volume.

**Comment by lkaupp** [comment]
Thanks for the feedback. I changed my version of asio4all v2 to 2.15 beta 3 instead of 2.14. After that, it was possible to max out the volume again and after a new calibration in Rocksmith everything works well and as expected. Thank you very much. Here is my config, you can add the Behringer Guitar 2 USB-cable to your working and tested list.

Rocksmith.ini:
```
[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1

....
```
RS_ASIO.ini:
```
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=320

[Asio.Output]
;Driver=ASIO4ALL v2
;BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by mdias** [comment]
Thanks! Added 👍

**Comment by MajkoHusenica** [comment]
Not sure if this is still active, but I setup everything the same way you did (ASIO4all v2.15) and I get a TON of noise. And I mean when the game loads up even the main menu guitar sounds weird. I dont understand if the issue is input or output.

**Comment by bercius** [comment]
I installed the RS ASIO files, and the guitar works, but the sound quality is poor. When I play the low E string, I hear crackling and whistling noises, especially towards the end. When I switch to the higher strings, the sound cuts off halfway. Even during the game’s startup screen, there is crackling noise.

I’ve tried adjusting the buffer size settings, but most of the time it got worse. I also tested with exclusive mode on and off. I changed SoftwareMasterVolumePercent to 60 and experimented with different values. I installed and tested ASIO4ALL versions 2.14, 2.15, 2.15 (beta3), and 2.16. I also went through the in-game calibration process.

Still, the sound is not satisfying, and the same whistling and cut-off issues remain. Is there a solution I might have missed? Or is it simply because the cable is low quality? Currently, I can’t find any stores selling the Real Tone cable in my country. Would getting an M-Audio M-Track Solo audio interface allow me to achieve satisfying sound quality and solve this problem?

rocksmith.ini: 
[Audio]
EnableMicrophone=1
ExclusiveMode=0
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=1
VisualQuality=2
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1

Rs asio:
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
