### ISSUE TITLE
RME Fireface UFX - USB - crashing

### ISSUE THREAD

**Issue by amosico2018** [mdias/rs_asio#257]
Driver :ASIO Fireface USB

Not works at all.. keep crashing right on the launch white screen with the logo on the bottom corner..
run 3 seconds and crush.. 

I Have both of the versions.. Rocksmith & Rocksmith Remaster 2014.. 
Both of them crash...

**Comment by mdias** [comment]
Does Rocksmith launch fine without RS ASIO?

**Comment by amosico2018** [comment]
Yes and yes.
I have Cubase, ableton live and they both works great with my rme ufx..
When I disconnect the RME USB from the pc, Tha game launch.. When I plug again inside the game it crash..

**Comment by mdias** [comment]
But does it work without RS ASIO and the interface plugged in?

The reason I ask is because if it does, you can likely work around the issue by using Voicemeeter as a middle man instead of having RS ASIO communicating directly with your device. It's annoying, but can solve some rare issues.
If it doesn't work with the interface plugged in and without RS ASIO, then the issue is somewhere else not related to ASIO.

**Comment by mdias** [comment]
Also note that this could be related to #106

**Comment by mdias** [comment]
@zagatozee Thank you for the heads up!
I just looked up and I assume [this is the fix/patch](https://github.com/Lovrom8/RSMods/blob/908043ffd27c12338317fea84c1fa10164da47d5/DLL/Mods/BugPrevention.cpp#L33) you mention.

Do you know if this just skips the crash but the PnP device still doesn't work, or does it actually skip the crash and also keeps the device working?
