### ISSUE TITLE
Motu M2: Problem with sound cutting

### ISSUE THREAD

**Issue by groundziro** [mdias/rs_asio#265]
Hello,

I have a problem with my new interface and rs_asio, I configured the interface with the help of a youtube tutorial and I cannot identify why the sound is cutting when i'm playing with my instrument through my interface.
I provided the *RS_ASIO.ini* in the file below and the log.
[RS_ASIO.ini](https://github.com/mdias/rs_asio/files/8134871/RS_ASIO.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/8134880/RS_ASIO-log.txt)

If anyone has an idea, i'll gladly take it.

**Comment by mdias** [comment]
Hello!

I just checked your config and log files and everything looks normal.
There isn't even any buffer underrun so everything appears to be working correctly on the ASIO side of things.

What do you mean by sound cutting? Is it all sound or only input stops registering? Also, does it cut for just a moment, or does it stop and never recovers?
Have you tested it with any other ASIO software?

**Comment by groundziro** [comment]
What is happening is that when I launch rocksmith with rs_asio installed, at first glance everything is working fine, then when I play a note with my instrument I have sound for a little bit then it stops completely then come back and then stops, this loop for 1-2 minutes.
Then the output doesn't produce any sound anymore. 
When I exit the focus of rocksmith *(alt-tab)* and wait for a little bit to comeback to reocksmith, sound comes back but the input isn't captured anymore.

But after I posted the issue, I found my old rocksmith cable to test it out and I found out that this problem weirdly enough is also present when I am using the cable. 
But when I am using the output on the computer and not on the interface sound doesn't cut and is perfectly fine.

For other ASIO drivers I only tested the one for my interface.
> Motu M Series

I had another interfac and I changed it recently, the other one worked but I started having problems with it that's why I changed it.

**Comment by mdias** [comment]
It sounds like Rocksmith could be detecting some timing anomaly. Can you ensure that your interface is set to run at 48kHz in both the interface drivers and also on the windows sound settings?

You could also try to use the interface as an input device and use the output on your computer for sound output. You can do this by setting `EnableWasapiOutputs=1` and leaving the `Driver=` part blank on the output section of the config file.

> Do you have any recommendation for other ASIO softwares that could work ?

Something like Guitar Rig, or FL Studio should do.

It is indeed a very odd issue you're having. If you have another computer where you can run Rocksmith you can check if it works there to see if it's a driver/software issue or an hardware issue.

**Comment by groundziro** [comment]
I tried everything at this point, I checked the interface is indeed running at 48k with 256 samples. 
I tried with the WASAPI outputs and the only difference is that the sound rocksmith doesn't cut directly but the input.

With Guitar Rig I had the sound cut not all the time but some short duration where I think it would freeze because the metronome was out of sync after it froze.

**Comment by mdias** [comment]
Right, it's interesting that a similar issue occurs with Guitar Rig. Altough it's a bit different I suspect the underlying issue is the same.
The probelm is that Rocksmith may decide to stop streaming in audio if it detects a big enough anomaly.

Right now I suspect your problem is either a hardware issue with the interface, or some other incompatibility with your system. For example, I have a system that often has issues with any audio interfaces connected through USB, altough on other machines it works fine.

I suggest you try your interface on another computer and try out also Rocksmith + RS_ASIO there, and maybe also Guitar Rig again. If the same issue persists in both of those scenarios, your interface likely has an issue and you may need to RMA it.
If it doesn't have an issue there, the issue is somewhere on your computer; could be either USB ports or some software setting. For example, there have been cases in the past where a clean windows install solved things, but your issue is weird enough that I kind of doubt it would..

Sorry I can't be more helpful.
