### ISSUE TITLE
It sounds like your cable is unplugged...

### ISSUE THREAD

**Issue by EPurpl3** [mdias/rs_asio#288]
Hello, 

i have tried everything and i cant make Rocksmith 2014 + ASIO to work. I keep getting the message (in game) "It sounds like your cable is unplugged..."

I am using a Behringer Xenyx QX1002USB connected to USB (default USB Audio CODED) and the ASIO4ALL drivers. I have setup ASIO in Audition to support 48k, i have configured RS_ASIO.ini and Rocksmith.ini and yet the game doesnt see the mixer

Here are the log and the ini's (renamed it to txt so i can upload it here).

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9015600/RS_ASIO-log.txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/9015601/RS_ASIO.txt)
[Rocksmith.txt](https://github.com/mdias/rs_asio/files/9015602/Rocksmith.txt)

Any help would be much appreciated especially because if i wont be able to ask for a refund on Steam soon. Thanks

**Comment by mdias** [comment]
Make sure your interface is running at 48000hz.
As stated in the readme this is a hard requirement.

**Comment by EPurpl3** [comment]
Hmm, thats strange, in ASIO Settings appears as 48000Hz.

![2022-07-01 10_08_14-Adobe Audition](https://user-images.githubusercontent.com/20075610/176843088-058688e4-fc9b-483d-af88-2990d35bf89f.png)

**Comment by mdias** [comment]
Strange indeed.
Have you tried using a DAW or similar that also uses ASIO4ALL with those configs to check the sample rate it can actually use?

The message in the log `unsupported sample rate: 48000` is printed after a direct request to the ASIO driver to check if it supports that sample rate.

**Comment by EPurpl3** [comment]
Thats quite hard to figure out because i cant select the game to use ASIO4ALL as the default driver. The ASIO4ALL (that appears as TI PCM2902 USB CODEC in the ASIO4ALL list) should use 48kHz as it does that on other apps. The Audigy also has ASIO drivers of it's own but i use it only for output. Unfortunately i have tried with both drivers and with the option 44.1kHz <-> 48kHz on and off but with no success.

**Comment by mdias** [comment]
> i cant select the game to use ASIO4ALL as the default driver

I'm not sure what you mean by this. With your config you don't need to select any drivers in the game, instead RS ASIO only provides the outputs and inputs to the game as specified in the RS_ASIO.ini file, so there's no chance for the game to select the wrong driver.

In any case, if this issue persists for you there's not much I can do since it's ASIO4ALL itself telling RS ASIO that it can't do 48kHz. If all the devices you selected in ASIO4ALL support 48kHJz and this error persists, the origin of the issue must be elsewhere. Perhaps ASIO4ALL uses your Windows settings and you didn't set that to 48kHz or similar...

**Comment by EPurpl3** [comment]
I will recheck everything when i will have time. It's good to know that i have configured the setting for RS_ASIO well. Thank you for the help.
