### ISSUE TITLE
Bass without sound

### ISSUE THREAD

**Issue by thehit180** [mdias/rs_asio#301]
Hey!
I'm using RS_ASIO for a while, works perfectly with guitars but when i change to bass, game did not get any signal from interface.
Is that only my problem or its common? Tried already on 3 different basses and results are the same.
After switching from "bass" to "lead" or "rhythm" the sound is back but its impossible to use a bass guitar that way :(

**Comment by mdias** [comment]
I'm going to assume the problem here is some kind of setting you have on your game.
The audio path is absolutely the same for guitars and bass, and there is no "bass mode" or "guitar mode" that RS ASIO negotiates with the game or anything like that, there's only audio wave going into the game.
So this should mean that you have something in the game somehow muting the bass.

**Comment by pedroadame** [comment]
@thehit180 not sure if it has something to do, but I needed to recalibrate inside Rocksmith after changing my guitar to my bass, even with Real Tone Cable. Otherwise RS would pick up no sound.
