### ISSUE TITLE
Add ESI MAYA22USB to the supported devices list

### ISSUE THREAD

**Issue by deadcombo** [mdias/rs_asio#32]
Hey, it's the Fender Mustang guy. I finally caved and got a proper USB interface and a DI box.

I figured this wouldn't warrant a pull request.

It's a game changer for sure, I have perfect note recognition now, all my scores went 10% down...

Anyway, thanks for this, it works brilliantly.

I do have a question, if you don't mind. Is it preferable to have a low USB buffer, or driver latency? I current have my driver set to 48ms latency and a buffer of 5. It's stable for all use cases like this,

I can lower the buffer up to 3 without playback problems, but I have to increase the latency or else the the output is dropped when the CPU load increases.

Mind you, I'm not complaining, this is what Ableton has to say about my current setup:
![ableton](https://user-images.githubusercontent.com/37187650/75048944-44ec9c80-54c1-11ea-8609-6c716dc7be8d.PNG)

**Comment by mdias** [comment]
Hello

I'm guessing when you say you have a buffer of 5 you mean on the
rocksmith.ini file?
If so, I don't know exactly how that setting works, but it appears to be a
number of queued-in-advance buffers in order to allow the game to have
processed buffers in queue ready for submission when driver asks for it.

So in the end, in regards to latency, both should be connected as the final
software latency should be number of buffers multiplied by buffer size.

For minimal latency you should reduce both as low as you can before you can
hear crackling.

And yes, decreasing these values will increase your CPU load in ways that
may or may not be visible on the task manager, so it will require
experimentation as each system can be very different.

**Comment by deadcombo** [comment]
No, my driver actually lets me set something called the 'buffernumber':
![buffernumber](https://user-images.githubusercontent.com/37187650/75099033-e6084f80-55b4-11ea-94ce-bb7da2b456c3.PNG)

[This thread](http://forum.mixvibes.com/viewtopic.php?t=18042) has some people talking about it, because unfortunately the manufacturer hasn't bothered to document it. It is a feature exclusive to the USB devices, and if I had to guess, it would have to do with USB buffers at a system level.

I actually get no crackling with the game's buffer at 1. There are some CLDCs that make my CPU go nuts though, I think that may be because of HIFI audio files (some charters use FLACs), or bad charts themselves. I thought it could be modeling too many effects, but official tracks with loads of effects run smoothly.

**Comment by mdias** [comment]
This seems indeed to be a driver-specific setting.
I would guess it's something similar to what I explained above for the rocksmith setting, but this should be for the whole audio driver stack. Though only the driver developer could tell for sure.

Thank you for the device report though, I will soon update the list :)
