### ISSUE TITLE
Behringer U-PHORIA UMC22

### ISSUE THREAD

**Issue by L0FKA** [mdias/rs_asio#326]
To get it working, install true ASIO driver [FROM HERE](https://drive.google.com/file/d/1jGTPi4cJ3iKDnPIHlOwjXljy3CYIigW-/view)
Also use a daw to set it to 16 bit 48000 Hz (as well as windows recording device settings)
[Reaper for example](https://cdn.discordapp.com/attachments/305406306821472257/1024917288203341824/256.jpg)

Connect your headphones to output of your UMC22
Config below is working, you may need to switch your input channel to 0 if you're using mic input instead of instrument.

[RS_ASIO.log](https://github.com/mdias/rs_asio/files/9912294/RS_ASIO.log)
(rename it to RS_ASIO.ini, or copy contents over)

**Comment by mdias** [comment]
Thank you for the report.
I've added it to the list 👍

**Comment by Awia001** [comment]
Out of curiosity, why does it require the use of the legacy Behringer ASIO driver? I can get it to work using that driver but then wasapi audio through the interface has a terrible popping that I cannot eliminate. And then I cannot get any audio from RS using ASIO4All as the driver in the RS_ASIO.ini.

**Comment by mdias** [comment]
@Awia001 ASIO4All is an ASIO "emulator", it does not communicate with your interface as effectively as a native ASIO driver does.

I'm not sure I understand why you're trying to use ASIO for input and WASAPI for the output if you still want to use the interface though?

**Comment by Awia001** [comment]
@mdias My apologies, I didn't explain myself fully. 
During gameplay I am solely using ASIO and that works perfectly when using the Behringer legacy driver, but then afterwards when I transition back to WASAPI for "normal" Windows audio there is constant popping in my headphones through the interface. This doesn't happen when using ASIO4ALL but then I cannot get ASIO audio in or out of RS even though ASIO4ALL works perfectly in Reaper and other ASIO applications.
In my setup I am using the interface as a headphone driver just generally and not just as an input/output for ASIO based audio.

**Comment by jessemodesto** [comment]
My installation keeps failing using the provided files for my UMC22.

I found the culprit.
In the busb2902.INF file there is line:
`
[BEHRINGER.NTAMD64]
%USB\VID_08BB&PID_2900.DeviceDesc%=USBDRIVER.Dev, USB\VID_08BB&PID_2900
%USB\VID_08BB&PID_2902.DeviceDesc%=USBDRIVER.Dev, USB\VID_08BB&PID_2902
`
The installation fails because my UMC 22 has the following VID & PID:
`
USB\VID_08BB&PID_29C2&REV_0100&MI_00
USB\VID_08BB&PID_29C2&MI_00
`

After modifying both INF files, running Inf2Cat for Windows 7x64, and disabling safeboot for testsigning (could not get the signing to work with signtool) the setup worked correctly and identified my UMC22. However the device fails to start (yellow sign in device manager) and other than being a usb device, does not include the sound controller in device manager (no audio output or input).

I am stuck here! I have not encountered anyone else with this issue (so far). It seems like my UMC22 got refurbished with different hardware? I am not sure. Unfortunately I have to continue using ASIO4ALL with the Generic USB Audio drivers.

**Comment by mdias** [comment]
@Awia001 sorry for the long delay; somehow I missed the notification of your message.
In any case, there isn't much I can do about it; it may very well be the case that RS_ASIO is somehow just not caring to fill the interface buffers with silence before quitting, and instead a part of the game's quit sound remains looping in the internal buffers.
RS_ASIO being just a translation layer, it sometimes lacks the easy ways to solve this kind of problem that would otherwise be simple to do on a normal ASIO integration, but at the end of the day the interface drivers should guarantee a good cleanup state after an application quits, and it seems you're missing that.

Unfortunately with a driver that is no longer supported you're also out of luck with emailing the company. :/

@jessemodesto Since no one else reported the need to edit the inf file, it looks like you might somehow have an actual different version of the interface which requires it's own drivers..?

**Comment by DonKerberos** [comment]
Is this okay ? i put it on Rocksmith.ini

[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=BEHRINGER USB AUDIO
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=1
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1

**Comment by DonKerberos** [comment]
Also I dont know why but reaper doesnt Record my guitar 

<img width="637" height="464" alt="Image" src="https://github.com/user-attachments/assets/f8ef8f0b-1405-4712-b066-8fa8cb138225" />

**Comment by DonKerberos** [comment]
I used this video as tutorial also https://www.youtube.com/watch?v=oJcW-PZBV8E&t=258s

**Comment by mdias** [comment]
@DonKerberos you shouldn't be editing `Rocksmith.ini` except to ensure that both `ExclusiveMode=1` and `Win32UltraLowLatencyMode=1` are set correctly. Please leave the `ForceDefaultPlaybackDevice=` empty.

What you want to edit is `RS-ASIO.ini`.

**Comment by DonKerberos** [comment]
Ok, thanks. I will try that.

**Comment by Hadrianneue** [comment]
just for record keeping, this device works fine on linux, no drivers needed as one would expect (may require patch bay setting up)

**Comment by stelimus** [comment]
Ive followed everything but for some reason it doesnt work. Logs say its crashing when trying to connect to the input.

**Comment by bernardopt123** [comment]
Hi , i have done everything that is said here , and now when i start the game it says "no output device detected" i can ignore the message and when i enter the game it says no realtone cable detected so i dont think it worked ( behringer uphoria umc 22) , is the problem the output device or it just dont work

**Comment by bernardopt123** [comment]
the thing thats worst is that it works perfectly in rocksmith plus , makes 0 sense , makes me wanna give up on both games

**Comment by Hadrianneue** [comment]
> Hi , i have done everything that is said here , and now when i start the game it says "no output device detected" i can ignore the message and when i enter the game it says no realtone cable detected so i dont think it worked ( behringer uphoria umc 22) , is the problem the output device or it just dont work

~~likely a problem with your wineasio setup, remember that you need to manually build wineasio, use proton 8 or 9 (preferably 8 since its easier to work with), put the dll's on your prefix, register them, and paste rs_asio into game folder and change config
i just follow this since im using pipewire/jack and arch: https://codeberg.org/nizo/linux-rocksmith/src/branch/main/guides/setup/arch-pipewire.md~~

**Comment by mdias** [comment]
I don't think he's trying to run it on linux.
But then again we have no logs, no config files and not much information, so who knows...

**Comment by bernardopt123** [comment]
rocksmit.ini 
[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=1
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1

rs_asio.ini

# Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=128

[Asio.Output]
Driver=BEHRINGER USB AUDIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=0
EnableSoftwareMasterVolumeControl=0
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=BEHRINGER USB AUDIO
Channel=0
EnableSoftwareEndpointVolumeControl=0
EnableSoftwareMasterVolumeControl=0
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

idk what logs are , this are the config files i guess , i tryed the no cable "mod" and i entered the game whitout the error but no sound comes out , i already put the 16bits 48hz thing on the headphones
in my country the cable costs 100 € ,if yall tell me it 100% works i will probably buy it , but im having trust issues whit this game already xd

**Comment by mdias** [comment]
@bernardopt123 the log file is the `RS_ASIO-log.txt` file.

Your config looks ok, however it doesn't let us know if you even have this `BEHRINGER USB AUDIO` ASIO driver installed.

You can also test your 32-bit ASIO driver with [this software](https://forum.vb-audio.com/viewtopic.php?t=1204), it contains both 64 bit and 32 bit little program. You should test with the 32 bit one because Rocksmith is a 32-bit application.

The original RealTone Cable should indeed work, but if you say you don't get any sound output with the no cable mod, the RTC will **not** fix that. Did you check if you get any output sound at all without any mods?

**Comment by bernardopt123** [comment]
@mdias yes , the game had sound before the mod , and I have the drivers installed ( I can play rocksmith plus perfectly and use amplitube etc )
I will try the 32 bit , makes sense , thanks

**Comment by mdias** [comment]
@bernardopt123 keep in mind the ASIO drivers are not the normal interface drivers. Unfortunately nowadays there are big manufacturers that also stopped shipping 32-bit ASIO drivers, and only ship their 64 bit ones instead.

There are workarounds for this, like using software that gets in the middle between RS ASIO and your 64 bit drivers to do the "translation", but it's ofc more annoying to use since you usually have to open this separate application before you launch the game etc. However it would fix the drivers issue.
If you're interested in that, look up [Voicemeeter](https://vb-audio.com/Voicemeeter/) but be prepared for a bit harder setup. It is easy once you understand how it works though.

**Comment by FroztMourne** [comment]
<img width="570" height="375" alt="Image" src="https://github.com/user-attachments/assets/66c7c67d-fbbb-42a8-8a03-e74593f2137a" />

installation always ends with error 0x0005 
Windows 11
Starting the installation with the interface disconnected didnt helps

**Comment by bernardopt123** [comment]
@mdias 1 month later I tried and it worked , idk what I did , I installed some mods and it made my aliexpress 10€ cable work , thanks
