### ISSUE TITLE
No audio output device is detected

### ISSUE THREAD

**Issue by MobilGame06** [mdias/rs_asio#378]
I use voicemeeter for a virtuel asio device because my mixer doesn't support it and the message comes up

rocksmith.ini
https://hastebin.com/share/ogizatilew.ini
rs_asio.ini
https://hastebin.com/share/jivusakaru.makefile
rs_asio-log
https://hastebin.com/share/eneropemel.yaml

**Comment by MobilGame06** [comment]
update i fixed it but now the guitar sound is crackling the rest of the game sounds normal

**Comment by mdias** [comment]
Please post a log resulting from a play session where you reached at least the main menu and heard the crackling sounds.

**Comment by MobilGame06** [comment]
https://hastebin.com/share/jixobokipo.yaml

**Comment by mdias** [comment]
I can see some xruns happening on that log, which explains the crackling sounds.

Usually we increase the buffer size to fix those, but you're already using a buffer size that is much bigger than what it should be for this game.
However since your device does not natively provide an ASIO driver this is expected.

The fix for the crackling would be to increase the buffer size in Voicemeeter, but that will result in noticeable audio latency.

Since your device doesn't provide a native ASIO driver anyway there why are you trying to use RS ASIO?

**Comment by MobilGame06** [comment]
because it is the only way i found which works somehow to connect my guitar via my mixer while hearing it in game (what you don't do when you select mic)

**Comment by mdias** [comment]
Direct Connect mode might be more suitable and provide much better results for you.
Look up "rocksmith direct connect"

**Comment by MobilGame06** [comment]
i tried that too but this just bugs out my whole sound (laggy)  so i hoped i can use rs_asio

**Comment by mdias** [comment]
That is strange. The game is supposed to have acceptable latency with a normal audio setup plus the RealTone Cable. I would expect direct connect to mostly work fine.

Which audio interface do you have?
And is there anything worth mentioning about it? (stuff like audio going through other devices etc)

**Comment by MobilGame06** [comment]
i use a behringer xenyx  q802usb which just goes throught voicemeeter

**Comment by mdias** [comment]
Looking at the list of supported interfaces, it seems people got the Behringer XENIX Q502USB working with the official legacy ASIO driver. Have you tried that?

**Comment by MobilGame06** [comment]
yeah but they are broken i can't even install them

**Comment by mdias** [comment]
Right... Not sure I can help further in that case.
