### ISSUE TITLE
Feature suggestion: Hotkey to enable multiplayer

### ISSUE THREAD

**Issue by janabimustafa** [mdias/rs_asio#38]
Hello!
Would love to have a hotkey (like ctrl+m) to enable multiplayer using RS_ASIO. That way I don't have to edit the ini file every time I switch between single player and multiplayer.

I am going to attempt making the changes required for this and creating a PR. 

Thank you so much for creating this awesome tool! It really changes the game and allows me to enjoy it without having to mess with the terrible cable and audio latency from Windows.

**Comment by mdias** [comment]
This would indeed be a nice feature to have, but it will require some other work to be done first regarding re-enumeration of audio devices.
I'll keep the issue open so it stays on the radar.

**Comment by pussyslayer624** [comment]
there is multiplayer?
how can i activate it?

**Comment by janabimustafa** [comment]
@pussyslayer624 Set the value of Driver inside Asio.Input.1

**Comment by darkdks** [comment]
This feature would be really useful and needed.
For now I made a small launcher (10 min of code) to help me with this (and my wife, too, she wouldn't understand editing the file).
https://github.com/darkdks/RSASIO_LAUNCHER

Btw, This project has been amazing, my wife and I have even returned to play since I can now play in low latency without noise and with her.
There is no words enought to say thank you mdias, but thank you for this!

**Comment by mdias** [comment]
The patch submitted in #236 should also help with this.
