### ISSUE TITLE
Reducing latency

### ISSUE THREAD

**Issue by kgreel** [mdias/rs_asio#391]
Hi
I'm experimenting with my Behringer UMC22 to try and reduce latency as there is a small noticeable delay.
In RS_ASIO.ini I've set:
BufferSizeMode=custom
CustomBufferSize=1
But I'm not sure it's having any effect as all I see is 128 or 256 in the RS_ASIO-log.txt file (which I've attached) no matter what value I set it to.

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/13184103/RS_ASIO-log.txt)

There is no 'control panel' for the UMC22, I'm using the 'legacy ASIO driver'.

If you could have a quick look, I'd be most grateful.

Thanks.

**Comment by mdias** [comment]
Hello,

`CustomBufferSize=1` would never work in any interface, this is way too low; in here you'd have something like `CustomBufferSizer=64` or similar.
However the values accepted here depend on what the driver reports too, and in this case you can see what the driver is reporting as supported in this line:
```
ASIOBufferSize - min: 256 max: 256 preferred: 256 granularity: -1
```

This means that the driver supports a minimum of 256 and a maximum of 256; in other words it's forcing you to use 256.
Some drivers provide an actual range here so that it allows the host application (in this case RS_ASIO) to choose a value within that range, some others don't provide a range to the host application, but will provide a range in the interface's control panel which is what I suppose is happening to you.

According to [this comment](https://github.com/mdias/rs_asio/issues/7#issuecomment-565814695) there should be a control panel for the legacy driver.
Go into your driver's control panel and change the buffer size there (the setting could be named something other than "buffer size"); that value should then be used by RS_ASIO.

Also notice that you only seem to be using ASIO for input and not output, so this will only affect your input latency, not the output latency.

**Comment by kgreel** [comment]
I managed to get it down to 128 without crackling audio and the delay has almost gone.

I'm using LatencyBuffer=1 in Rocksmith.ini

I could only use RS_ASIO for output by setting ExclusiveMode=1 but then the audio was completely distorted and weird.

Thanks for your help.

**Comment by mdias** [comment]
No problem.

RS_ASIO requires ExclusiveMode to be on, that's correct.

Usually disabling that results in significant latency increase, so that could explain why you have high latency. If your input through RS_ASIO works fine, I would expect the output to work fine as well as long as you're using ASIO for output as too.
