### ISSUE TITLE
Rocksmith Rs.Asio DLL

### ISSUE THREAD

**Issue by flashbecker** [mdias/rs_asio#394]
Hey I have an issue with my rocksmith to start…a message appears saying this
![IMG_7678](https://github.com/mdias/rs_asio/assets/149852798/c2ed3daa-f599-4567-ae74-4a90c96aa42a)
Here my files 
![IMG_7679](https://github.com/mdias/rs_asio/assets/149852798/e6a8ab00-d1a7-4db3-949f-5de3b352cfea)

![IMG_7680](https://github.com/mdias/rs_asio/assets/149852798/4c605221-9063-483a-a595-68c63b501a89)

What should I do

**Comment by mdias** [comment]
Do you have the RS_ASIO.dll file in the game folder?
If so, view the file's properties to check that it's not blocked by windows (because it was downloaded from the internet) or that any antivirus programs are not disallowing access to the file for the same reason.

You don't have a valid config file yet, but that error is coming before RS_ASIO even starts.

**Comment by flashbecker** [comment]
i saw and everthing is unblocked...but i couldn´t found rs asio.dll file..what should i do now hahaha

**Comment by mdias** [comment]
download RS_ASIO again; it's in the same zip file as `avrt.dll` and `RS_ASIO.ini`

**Comment by flashbecker** [comment]
where exactly are those files,i need a step by step for this things and my game keeps appearing message with rs asio dll

**Comment by mdias** [comment]
You're downloading the source; those are not the right files you need.

If you look into the instructions in the main page it has a link to the [latest release](https://github.com/mdias/rs_asio/releases/latest). There you'll find the zip file with the DLLs and the ini file.
