### ISSUE TITLE
Doesn't recognize thunderbolt devices

### ISSUE THREAD

**Issue by robrogers** [mdias/rs_asio#40]
I've got an Apollo Twin MkII thunderbolt and it's not showing up in the log. Reaper and cubase see it just fine since i use it for recording. attached my log file if that helps
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4332972/RS_ASIO-log.txt)

**Comment by mdias** [comment]
We can actually easily see on the log that your interface is well recognized and initialized, which makes sense since RS-ASIO has no concept of USB/Thunderbolt or something else.
Your issue is probably the fact that you're using a 512-frame buffer which Rocksmith itself won't like. Try something like 128 or lower.
