### ISSUE TITLE
Rocksmith has been delisted now. Is there still a way to obtain the Steam version of the game?

### ISSUE THREAD

**Issue by zhaolin-st** [mdias/rs_asio#410]
Is this possible at all with the cracked version as there is no way to obtain the game now without piracy.

**Comment by mdias** [comment]
I understand the frustration, but I won't be providing support for any pirated version of the game.

**Comment by VegaDeftwing** [comment]
I understand the moral ambiguity here, but I'm going to look into making my own fork to do this for a few reasons:

* The delisting isn't in a vacuum. Ubisoft did this because they want to sell Rocksmith+, which is $100/yr, dramatically more expensive than the on-device version while simultaneously depriving the user of ownership since, yunno', subscription.

* This patch/mod already exists due to a money-grab: We all know their cable is worse than a real interface.

* Rocksmith+ wouldn't be nearly as popular if it weren't an already established product, building off the good will of a community that found the last two releases good in part due to mod/patches _like this one_. 

* I own the game, but updates have made setting up mods like this and the community made song packs harder to install or just break occasionally. If I were to run a pirated version - even owning the game already - I can be sure this won't happen.

* I own the game, but unlike the good ol' days of disk sharing or bringing a game to a friends house, I can't do that easily with Steam. There is Family Share, but I don't even know if that will continue to work with the delist. - If buying isn't owning, piracy isn't stealing.

* This isn't anything new from Ubisoft - https://www.videogameschronicle.com/news/ubisoft-has-officially-shut-down-online-services-for-over-90-games/ - I don't even trust RS+ to continue to operate well if I did recommend someone else pay for it.

I'm mostly here because my dad got into guitar on new years and I wanted to help him learn the same way I did over a decade ago on the original RS and then continued to on RS2014. I know the cable is a massive POS (I broke two of them!) and that the non-asio cable-skip mods also have problems. Your work here is fantastic, and it would be a shame to let the greed of Ubisoft put such an ugly cap on it.

**Comment by mdias** [comment]
Please understand I'm not being dismissive of your opinions here, but I will personally not be supporting a pirated version of the game for many reasons; some of those will be obvious while some others might not.

I'm glad you got to be one of the people that is able to enjoy RS ASIO even though you're having these issues. I've seen people suggest looking around for sealed physical copies of the game (I presume with a steam key inside) so maybe that helps.
