### ISSUE TITLE
Does this work with Behringer U-Phoria UM 2?

### ISSUE THREAD

**Issue by SAARussian** [mdias/rs_asio#5]
Its audio device have only 16 bit amps...

**Comment by mdias** [comment]
At first sight I would say no. However it's not impossible that it (or it's drivers) would accept 24-bit samples even if the actual processing resolution is only 16-bit.

It's worth a try. If it doesn't work because of this, the reason will be stated in the log file it generates. I would encourage you to post the log on pastebin and link it here too. Basically adding support for 16-bit interfaces should be fairly easy, but I don't have such hardware with me to actually test it...
