### ISSUE TITLE
Odd debugging/ Scarlet Solo 2nd gen not working;

### ISSUE THREAD

**Issue by Ub3rZ4cH** [mdias/rs_asio#51]
**Background:**
Okay so I have a realtone cable but I want to use my scarlet, so I googled some and ended up here, using ASIO. So I installed ASIO4ALL and installed this and I had sound but it was crackly and I kept messing with the buffer size and latency buffer to no luck (changing them made it much slower and worse), eventually I saw that you need a device that supports 48khz, mine was 41 in ASIO, I googled some and it turns out installing the Scarlet driver fixes this.

However this opened up a new issue, previously I had used ASIO4ALL v2 under find drivers, and I had no sound at all and a red exclamation mark, but then I noticed the known issues saying (Doesn't provide a way to open the ASIO control panel), so I figured I was doing something wrong, I looked into the log and saw a new thing listed under find drivers "Focusrite USB ASIO" so I change to this, and I can hear the game perfectly now... with one small issue, It wont detect my guitar! Since I can not open the ASIO control now to check if its using my device, I disabled everything but my scarlet in windows.

**My issue basically TLDR:** 
The game audio works fine, but rocksmith does not detect my guitar, in fact it detects TWO realtone cables??? when I select microphone when going to tuner it says "it sounds like your mic is unplugged" and if I switch it realtone cable when going to tune it says "two realtone cables are detected we cant tell which one youre using, disconnect one of them"

**Comment by Ub3rZ4cH** [comment]
[](https://github.com/mdias/rs_asio/issues/14#issue-544814105)
Pottentially the same as this, I just looked at the error 

> 26.904 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.904 [ERROR]    failed to initialize asio driver with requested format

How ever the fix acording to this closed issue was to download the correct version I downloaded 0.4.2 from releases?

**Comment by mdias** [comment]
There is no fix for the IEEE Float error, that is expected if your interface doesn't support floating-point format, and it's not a show stopper.

As for detecting 2 cables, I'm guessing you filled the driver name in both Audio.Input.0 and Audio.Input.1.

And you probably don't hear anything because you likely have the wrong channel selected in Audio.Input.0. You see, your interface has 2 inputs, but the first one (Channel 0) is a microphone input and so you have your guitar connected in the 2nd input, which is Channel 1.
Leave your Audio.Input.1 Driver setting empty, and set Audio.Input.0 Channel to zero.

**Comment by Ub3rZ4cH** [comment]
Ah okay, thank you ! it works now.

I am dumb I thought I just had to pick the chanel in game, but you got to do it in the config.

**Comment by mdias** [comment]
Good to hear! Enjoy :)
