### ISSUE TITLE
Apollo thunderbolt not recognised

### ISSUE THREAD

**Issue by Carrollie** [mdias/rs_asio#57]
Thanks for your awesome work.

I have a UAD apollo twin connected via thunderbolt.
When the UAD ASIO is installed, 3 different UAD ASIO versions seem to be created:
Universal Audio Apollo Firewire
Universal Audio Apollo Twin USB
Universal Audio Thunderbolt

When I use Ableton Live, I have to use the third option (Universal Audio Thuderbolt).  The other 2 options don't work (must be for other UAD devices)

The log file from rs_asio seems to only show the first two ASIO versions and does not show the option for Universal Audio Thunderbolt

Is there an easy fix for this?

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4532257/RS_ASIO-log.txt)

Thanks

Andrew

**Comment by mdias** [comment]
Can you also post your RS_ASIO.ini file?

**Comment by Carrollie** [comment]
I managed to get it working using my zoom H6 recorder which can work as an ASIO audio interface.  Not an ideal option but it works!

This is the RS_ASIO.ini at present (with the H6):  
[RS_ASIO.zip](https://github.com/mdias/rs_asio/files/4533901/RS_ASIO.zip)

I have also put the lastest .log file as well for what it is worth.

Thanks again

**Comment by mdias** [comment]
Good to know it's working with the Zoom H6 :)

Can you please share the RS_ASIO.ini that you tried with the UAD Apollo Twin and didn't work?

**Comment by Carrollie** [comment]
Here are the ini and log files.
I have put three different versions.  Two of them I did not think would work as they were for the USB and firewire versions of my device (but I used them as they at least appeared in the log file).  The third version I used the name that appears in the Ableton Live audio selection setting "Universal Audio Thunderbolt"  (which also shows the other 2 universal audio ASIO devices (firewire and twin usb) that appear in the RS_Audio-log.txt file)
I hope that makes sense.

Thanks

[RS_Audio_ini_logs.zip](https://github.com/mdias/rs_asio/files/4536468/RS_Audio_ini_logs.zip)

**Comment by Carrollie** [comment]
I think the UAD Apollo Thunderbolt is set up differently to other Audio devices.

When I turn on the H6 Zoom recorder, I see it appear in Device Manager in "Sound, Video and Game Controllers" and also "Audio Inputs and Outputs" 

The UAD Apollo (Universal Audio Apollo Twin Thunderbolt) appears in "Audio DSP Accelerator " which already has a UAD-2 System Driver in it.

In Audio Inputs and Outputs there is a Speakers(Universal Audio Thunderbolt WDM). Which I think is how Universal Audio lets windows use their device.
"Sound, Video and Game Controllers" also has an entry for Universal Audio Thunderbolt WDM which is there whether the apollo is turned on or off.

Not sure if this helps  (sorry I am not very savvy with this stuff)

Cheers

Andrew

**Comment by mdias** [comment]
Here's what I found on the configs and logs that you uploaded:

- `First Run with ini` -> No drivers are specified in the ini file. I'm guessing you are replicating all your steps and purposefuly running without drivers first in order to look at the log file and see which ones are available.
- `UAD firewire` -> The driver is reporting that it can't open the firewire audio interface, which according to what you said is normal and expected.
- `UAD thunderbolt` -> You specified `Universal Audio Thunderbolt` on the drivers, but there is no such **32-bit** ASIO driver found on the system.
- `UAD twin USB` -> The driver is reporting "No device is connected to the PC." which also makes sense according to what you said.

So, according to the logs, these are the **32-bit** ASIO drivers installed on your system:
- Blackmagic ASIO Driver
- Maschine MK3
- Universal Audio Apollo FireWire
- Universal Audio Apollo Twin USB
- ZOOM H and F Series ASIO
- ZOOM H and F Series Async ASIO
- ZOOM H and F Series Multi ASIO

Keep in mind that since Rocksmith is a 32-bit application, you need 32-bit ASIO drivers installed for it. So in your `UAD thunderbolt` case perhaps you have a `Universal Audio Thunderbolt` driver installed but only it's 64-bit variant?
