### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by SAARussian** [mdias/rs_asio#6]
There is no sound in Rocksmith 2014 Remastered with nocable patch through behringer uphoria um-2 on windows 10
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/3909781/RS_ASIO-log.txt)
![image](https://user-images.githubusercontent.com/57723354/69935749-e083f780-14e6-11ea-9d93-93b33f7a437a.png)

**Comment by jtb-ship-it** [comment]
According to the log file your behringer device has not installed asio drivers.

**Comment by SAARussian** [comment]
I use asio4all this standart driver for my behringer

**Comment by mdias** [comment]
Can you post also your RS_ASIO.ini file?

I tested ASIO4ALL v2 output locally with my onboard audio and it seems to work fine.

**Comment by SAARussian** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by SAARussian** [comment]
![image](https://user-images.githubusercontent.com/57723354/70004406-30aa9a80-1577-11ea-92ab-699a0842ec08.png)

**Comment by mdias** [comment]
Your `Driver=` settings need to be `Driver=ASIO4ALL v2` for both Output and Input.0.

The first time you boot the game you may not have any sound, keep the game running (in windowed mode) and open the ASIO4ALL control panel (you should have an icon on the system tray).
There you should enable 1 output and the guitar input too for your Behringer device. Start with a buffer size of 144.
After this, you need to restart the game as it doesn't support dynamically applying ASIO changes as of now.

If this works, you can try going lower on your buffer size to improve latency, but every time you change, you need to restart the game.

**Comment by SAARussian** [comment]
Still no sound, I tried different buffer sizes

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/3914401/RS_ASIO-log.txt)
![image](https://user-images.githubusercontent.com/57723354/70018060-f997b180-1595-11ea-875c-57357d2e340f.png)

**Comment by mdias** [comment]
Everything looks right except for the buffer size.
I know you said you tested several, but did you try 144 or lower? Rocksmith doesn't like much bigger sizes than that, so that may be the issue. Don't forget to restart rocksmith after changing it.

Also try 144 with another ASIO application to make sure that this size isn't an issue with the driver/device.

Other than that everything looks fine in the log output, so it should work. It's also nice that even though your audio interface is 16 bit, ASIO4ALL seems to create this 32-bit layer in between which I would guess it's to improve compatibility, so that shouldn't be an issue.

**Comment by SAARussian** [comment]
I have much to say))
1st: I had no sound until I made a large buffer size in rocksmith.ini (4 latency buffer)
2nd: I had audio crackling with any audio parameters until I checked "Always Resample 44.1 kHz <-> 48kHz" and "Force WDM Driver To 16 Bit" in my asio4all driver, аnd the sound quality got better. Then I have unchecked this parameters and sound quality still good.
3rd: I need to use my second input (Hi-Z instrumental) channel. I set [Asio.Input.1] to:
Driver=ASIO4ALL v2 and in game setting I choose  microphone (and there was a choice of two real tone cable) and I choose 2nd real tone. 
Did I do it right? The level of input delay and sound quality is better or the same than through the original real tone cable?

**Comment by mdias** [comment]
You don't need to enable "Input.1", that's only needed for multiplayer.
You can just change "Channel=0" to "Channel=1" on "Input.0" so that Rocksmith uses your second input on your interface and this way you won't get the message about 2 cables being connected.

Unfortunately your device doesn't appear to support real ASIO, which is why you're having these issues, as ASIO4ALL is just a layer to add "ASIO compatibility" on top of WDM.

Generally with ASIO your latency should be better than with the original real tone cable, but keep in mind the ASIO implementation of your device is on top of WDM so we can't make assumptions.
As for quality, it depends on the quality of the inputs of your device. The only way to know the answer to this is to test it.

Since your interface doesn't have real ASIO support, there's probably no real gain of using RS_ASIO over something like NoCablePatch, unless that gives you issues of course.

As for using "play through microphone", that will disable all the guitar amp simulation so you won't hear your guitar with effects ingame.

**Comment by SAARussian** [comment]
I just doing like this, and don't get message about two cable connected 
![image](https://user-images.githubusercontent.com/57723354/70096887-2d77e300-1639-11ea-9854-92bcf6ac8ee4.png)
In DAW asio4all works fine on 48khz + 256 buffer size. Input delay about 7ms
![image](https://user-images.githubusercontent.com/57723354/70097095-a840fe00-1639-11ea-9e0d-18f3c8ec94bc.png)
I have another one asio driver http://yamaha-petropavlovsk.ru/zagruzki-2/drayvera-dlya-zvukovoy-karty-behringer-u-phoria-um2 it used to be supported by the manufacturer, but now it is not.
I using "play through microphone" to change my input channel, then the game throws me back to the real tone cable mode

**Comment by mdias** [comment]
Ahh yes, that config works too, and should be essentially the same as using Channel=1 on the Input.0 :)

256 sample buffer size should give you a total latency above 7ms, as the buffer alone is 5ms big and you need one for input and another for output; plus there should be a bit more latency added due to USB overhead.

Even with onboard audio cards you should be able to hit 144 sample size for improved latency.

You shouldn't need to use "play through microphone", but if you can get it to work like that then I guess it's fine :)

**Comment by SAARussian** [comment]
My behringer u-phoria um 2 can't handle lower that 256 on 48 khz, it will be lagin crackiling sound. Or I can use 224 on 44 khz. Also, I can use officially not supported now by the manufacturer asio driver. With him delay equal 0 MS

**Comment by mdias** [comment]
I see. There is nothing else we can do then.

As long as it still works fine for you at 256 then it's ok :)

**Comment by SAARussian** [comment]
Thank you)

**Comment by SAARussian** [comment]
Oh... This feature ignoring rocksmith.ini latency buffer settings? xD

**Comment by mdias** [comment]
Probably not. I'm not entirely sure what LatencyBuffer option does, but I think it queues several buffers to send/receive to the driver (in this case RS_ASIO).

I don't know for sure unfortunately...
