### ISSUE TITLE
Question about Rs_asio

### ISSUE THREAD

**Issue by SiiNerGia** [mdias/rs_asio#60]
hello, first, sorry for opening an issue for this but i cant quite think of a way to contact you that is not this one.

My question is, does rs_asio improve latency performance for users that dont have an external interface, and that have the guitar directly conected to the pc via line in and then Asio4all installed?

Thank you

**Comment by mdias** [comment]
Hello. It's fine to contact me this way, and is actually the intended way so that all information about RS ASIO is centralized in one place :)

Your question is difficult to answer with certainty because there are many variables. However it will usually be the case that latency is improved.

To explain a bit more, ASIO4ALL is compatibility layer so that you can have ASIO-only applications working with any audio interface that you have even if that doesn't provide it's own "proper" ASIO driver. That means that the way it interfaces with your audio card is by going through some other layers that usually results in higher latency.
A "proper" ASIO driver usually has a much more direct interface to the audio interface and because of that it will usually have lower latency.

Now, each audio interface is different and the way it's hardware/firmware is designed as well as how it's ASIO driver is designed you may get better or worse latency. Even your own motherboard and CPU may have an impact on this. So getting an audio interface that is rated for X amount of latency will only ensure you that the interface itself is capable of that, but the rest of your system may not be so.

Assuming you don't have any substancial issue with your PC, using a good interface will usually result in very good latency and you shouldn't have too many issues. However some people decide to go very cheap on an audio interface and that may cause them to have a bad experience and maybe even worse audio quality than compared to their onboard audio interface.

To to sum it up, as with everything, it's always best to do some reading and investigation; reading reviews of interfaces and all that so you build up a good idea of what is good enough for you.

Hope it helps :)
