### ISSUE TITLE
Will it work with microphone? 

### ISSUE THREAD

**Issue by SAARussian** [mdias/rs_asio#79]
I have behringer u-phoria um2 audio interface and my guitar world perfectly with rs_asio is 1st and 2nd input channel, But I wanna buy xlr mic for karaoke in RS, would rs_asio work for it at the same time with guitar?

**Comment by mdias** [comment]
This depends on what you mean. If you mean to ask if the microphone would somehow be heard by Rocksmith, then no, as long as you have the proper channel configured for the guitar, RS_ASIO will use just that and ignore stuff connected to other channels.

Now depending on what you plan to do to hear the microphone, you may or may not have issues. Basically if you plan on having some other software listening to the mic (and probably playing through speakers after that) then it depends on whether your ASIO drivers will allow multiple apps accessing the ASIO device or not. You can test this before buying the mic though.

Now if you want to connect your mic there, and route only the mic signal to some other device through hardware (which I'm not sure if the u-phoria um2 can do) than this ofc is something RS_ASIO couldn't interfere with even if it wanted to.

**Comment by SAARussian** [comment]
just wanna use my AI for guitar and singing in RS (it have nice karaoke system) without any other DAW or something

**Comment by mdias** [comment]
What is this karaoke system? Is this a software on your computer, or something else?

**Comment by SAARussian** [comment]
> Что это за караоке-система? Это программное обеспечение на вашем компьютере, или что-то еще?

EnableMicrophone=1
in rs

**Comment by SAARussian** [comment]
just wanna use my 1st input channel like mic, not like second guitar player

**Comment by mdias** [comment]
This `EnableMicrophone=1` is supposed to work for accoustic guitars, not for karaoke.

In any case RS_ASIO presents itself to Rocksmith as a RealTone Cable currently, so it probably won't work if you try this.

**Comment by SAARussian** [comment]
not its option for singing)

**Comment by SAARussian** [comment]
Maybe I can help you something? Or is it impossible to implement at the .dll level?

![image](https://user-images.githubusercontent.com/57723354/85890784-b8e3dc00-b7f6-11ea-9ca0-2de1d982a84e.png)

**Comment by mdias** [comment]
It probably would be possible to implement detecting inputs as mic inputs, however the channels would still be separated, which means one player would use a mic, while the other would use a guitar.

I didn't try having the game detect an input as a normal mic input, but if there are no surprises it should be fairly easy to do this. You'd create a new "RTCCable" setting per input channel on the .ini file, and then depending on whether that is enabled or not the input would present itself as a normal input or RTCable input.

If you want a single player to use both guitar and mic then the problem is bigger as you'd have to mix 2 inputs for this.
One thing to keep in mind is that Microphone Mode disables the amp sound effects.

**Comment by SAARussian** [comment]
Yeah that what I want, sing and play, 1st channel for mic w/o amp sound, but in-game area effect. And 2nd for guitar playing like realtone cable 

> If you want a single player to use both guitar and mic then the problem is bigger as you'd have to mix 2 inputs for this.
> One thing to keep in mind is that Microphone Mode disables the amp sound effects.

**Comment by mdias** [comment]
I will see what I can do if I find some time.

**Comment by SAARussian** [comment]
Probably impossible ... :(

**Comment by mdias** [comment]
@SAARussian sorry it's taking so long to have a proper reply to this. I might likely have some time probably before end of year, but one of the issues that I'll have is that I don't own an XLR mic. Maybe it's not an issue, since I can plug the guitar there just to see if the sound goes through.

I didn't  forget about this though.

**Comment by mdias** [comment]
@SAARussian I've just made a [new release](https://github.com/mdias/rs_asio/releases/tag/v0.5.5) that should have this working.

Check the included config file. You'll need to add `[Asio.Input.Mic]` to your current config and configure it just like any other input.
Let me know if it works fine for you :)

**Comment by SAARussian** [comment]
@mdias Unfortunately my microphone is broken... My microphone is broken, so I'm waiting for a new one to arrive, I'll report it later.

**Comment by mdias** [comment]
No worries :)

**Comment by SAARussian** [comment]
ITS WORKING!

**Comment by mdias** [comment]
Awesome news! I'll make the pre-release a normal release then :)
