### ISSUE TITLE
Says I have 2 Realtone cables plugged in after I installed it.

### ISSUE THREAD

**Issue by SethFitzwater** [mdias/rs_asio#81]

**Comment by mdias** [comment]
Can you be more descriptive?

What interface do you have and what does your config file look like?

**Comment by freecodecampster** [comment]
I also got that message because I had supplied a driver argument for both [Asio.Input.0] and [Asio.Input.1]. On my Yamaha AG06 2 channel Mixer my electric guitar is plugged into the second input or right channel. So I leave the driver field vacant for [Asio.Input.0] and provide Yamaha Steinberg USB ASIO for the driver field for [Asio.Input.1]. After that the error went away and Rocksmith thinks I have only one real tone cable attached.

So I would check your RS_ASIO.ini file. Here's mine for reference.


[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=48

[Asio.Output]
Driver=Yamaha Steinberg USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Yamaha Steinberg USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
Yes, this is actually a feature of rs_asio to allow multiplayer mode for interfaces that have multiple inputs, or actually multiple interfaces :)

**Comment by freecodecampster** [comment]
> Yes, this is actually a feature of rs_asio to allow multiplayer mode for interfaces that have multiple inputs, or actually multiple interfaces :)

Many, many thanks Micael for making this @mdias. It works beautifully with my Yamaha AG06 USB Mixing Console. [https://uk.yamaha.com/en/products/music_production/interfaces/ag_series/index.html#product-tabs](url)
