### ISSUE TITLE
Can't get UMC 202 HD to work.

### ISSUE THREAD

**Issue by zionhian** [mdias/rs_asio#9]
![image](https://user-images.githubusercontent.com/42749792/71542113-1c39a200-296b-11ea-9c49-ee2c3cd18f06.png)
![image](https://user-images.githubusercontent.com/42749792/71542118-25c30a00-296b-11ea-8c6c-41fa27fca59a.png)
![image](https://user-images.githubusercontent.com/42749792/71542121-35dae980-296b-11ea-9843-a9763d9a79da.png)
![image](https://user-images.githubusercontent.com/42749792/71542122-383d4380-296b-11ea-9d8f-ba4981d9b205.png)
![image](https://user-images.githubusercontent.com/42749792/71542128-45f2c900-296b-11ea-9090-288db4586413.png)
![image](https://user-images.githubusercontent.com/42749792/71542129-48edb980-296b-11ea-88d8-4a135bbc5f55.png)
When i run the game i get this: 
![image](https://user-images.githubusercontent.com/42749792/71542138-628f0100-296b-11ea-998e-751fd94237e4.png)

**Comment by zionhian** [comment]
Also the RS_ASIO log file does not appear in my game folder.

**Comment by mdias** [comment]
You probably want to use `UMC ASIO Driver` on the driver config instead of the device name. This field wants the ASIO driver name, not the device name.
It's also a red flag that the log file isn't being generated. Perhaps the directory is write protected?

**Comment by zionhian** [comment]
I'll move the game from my C drive to my D drive and i'll update you on what happened later.

**Comment by zionhian** [comment]
I moved to my D drive. Tried using UMC ASIO Driver on the config and it still gave me the same error and didn't generate a log file either. The directory it's is not ready-only. Also after downloading the files i made sure to unblock them ( right click and properties). My AV is malware-bytes and i have my entire steam folder whitelisted in windows defender. I ran the game through admin, in compactability mode, etc. Is there any program i need installed ( visual studio redist, xna or stuff like that). Also just making sure that this does work with the remastered version of the game or do i need the old one ?

**Comment by mdias** [comment]
This is for the 2014 remastered edition of the game. It's very strange that you don't get the RS-ASIO-log.txt while at the same time it seems like the patch is running (since you have that error popping up, it's probably running, but just not configured yet).

You should still try to configure it by using `Driver=UMC ASIO Driver` as stated above, as you have an interface known to work.

I have no idea why the log file isn't there though; it should load the .ini config and output the log file in the working directory, which by default is the game folder.
